### ISSUE TITLE
Upgrade to HA 0.112.0: TXStatus.NWK_ROUTE_DISCOVERY_FAILED

### ISSUE THREAD

**Issue by DanielBaulig** [zigpy/zigpy-deconz#119]
I've been having trouble with my Conbee II. Since I upgrade to Home Assistant 0.112.0 all my Zigbee devices have been Unavailable. I'm seeing the following message in my logs:

```
[zigpy_deconz.zigbee.application] Error while sending 28 req id frame: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
```

I've googled for TXStatus.NWK_ROUTE_DISCOVERY_FAILED and I've been literally getting no hits for it.

I tried re-installing the ZHA integration, rebooting the host, unplugging an replugging the Conbee II, unplugging and replugging some of the Zigbee devices (specifically routers). Nothing seems to help.

**Comment by Adminiuga** [comment]
Enable full debug (see zha integration docs) and please post the log file (or DM me on discord) after a restart.

**Comment by DanielBaulig** [comment]
@Adminiuga: I have since entirely removed the integration and set it back up again. It is now working again. Because of that I can't provide the exact logs anymore. :-/

Note though that just removing and reinstalling the integration itself didn't actually fix the issue. I had to move/delete the zigbee.db and .storage/zha.storage files. I do still have copies of the old files if that might be helpful to you.
