### ISSUE TITLE
How can I get network information and firmware version of Deconz

### ISSUE THREAD

**Issue by zoic21** [zigpy/zigpy-deconz#131]
Hello,

I build an plugin for french smarthome solution, I use zigpy to handle zigbee device, it's perfectly work. Now I need to get network information (PAN ID, ext pan id...) from deconz how can I get that ? I also need firmware version. 

With ezsp I used `ZIGPY._ezsp.getNetworkParameters()` is there the same kind of function for deconz?

Thank in advance

**Comment by Adminiuga** [comment]
Some are available as properties of the Controller application after a successful startup, others could be read as Network parameters. See https://github.com/zigpy/zigpy-deconz/blob/9ee4440f267e10066541c23ff956a22fb2523d2f/zigpy_deconz/zigbee/application.py#L82-L91

**Comment by zoic21** [comment]
Thank I test but all data is at None : 

`{'_send_sequence': 1, 'devices': {00:21:2e:ff:ff:03:b4:a4: <zigpy_deconz.zigbee.application.DeconzDevice object at 0x7f2cf52f1128>, 00:17:88:01:02:01:72:29: <zigpy.device.Device object at 0x7f2cf5bbff28>, 84:2e:14:ff:fe:20:4d:58: <zigpy.device.Device object at 0x7f2cf5bbffd0>, 00:15:8d:00:04:44:75:d9: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5344c88>, 00:15:8d:00:02:f9:25:0b: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5344d30>, 00:15:8d:00:02:79:5a:70: <zhaquirks.xiaomi.aqara.wleak_aq1.LeakAQ1 object at 0x7f2cf5350208>, 00:15:8d:00:03:16:d5:ce: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5350630>, 00:15:8d:00:02:36:f1:23: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5350860>, 00:15:8d:00:02:51:87:51: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5350be0>, 00:15:8d:00:02:52:b0:38: <zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2 object at 0x7f2cf5344eb8>, 00:15:8d:00:02:57:a2:09: <zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2 object at 0x7f2cf5359320>, 00:15:8d:00:02:71:6e:44: <zhaquirks.xiaomi.aqara.wleak_aq1.LeakAQ1 object at 0x7f2cf5359710>, 00:12:4b:00:1c:d6:0c:42: <zigpy.device.Device object at 0x7f2cf5bc9160>, 00:12:4b:00:1b:78:1d:51: <zigpy.device.Device object at 0x7f2cf5bc9630>, 14:b4:57:ff:fe:d3:e0:95: <zigpy.device.Device object at 0x7f2cf5bc96d8>, 08:6b:d7:ff:fe:20:23:fd: <zhaquirks.ikea.twobtnremote.IkeaTradfriRemote2Btn object at 0x7f2cf5359e80>, 00:0d:6f:ff:fe:9c:d2:81: <zhaquirks.ikea.blinds.IkeaTradfriRollerBlinds object at 0x7f2cf5344f28>, 00:0d:6f:ff:fe:7b:7d:4b: <zhaquirks.ikea.opencloseremote.IkeaTradfriOpenCloseRemote object at 0x7f2cf52e47f0>, d0:cf:5e:ff:fe:03:90:fa: <zigpy.device.Device object at 0x7f2cf5bc9978>}, '_listeners': {139831078023576: (<zigpy.appdb.PersistingListener object at 0x7f2cf5bbf198>, False), 139831068792088: (<mainListenner.MainListener object at 0x7f2cf52f1518>, False)}, '_channel': None, '_channels': None, '_config': {'database_path': '/var/www/html/plugins/zigbee/data/network_deconz.db', 'device': {'path': '/dev/ttyACM1'}, 'network': {'channel': 15, 'key': None, 'update_id': 0, 'tc_link_key': [90, 105, 103, 66, 101, 101, 65, 108, 108, 105, 97, 110, 99, 101, 48, 57], 'extended_pan_id': None, 'tc_address': None, 'channels': <Channels.CHANNEL_25|CHANNEL_20|CHANNEL_15: 34635776>, 'pan_id': None, 'key_sequence_number': 0}, 'ota': {'otau_directory': None, 'ikea_provider': False, 'ledvance_provider': False}, 'watchdog_ttl': 600}, '_dblistener': <zigpy.appdb.PersistingListener object at 0x7f2cf5bbf198>, '_ext_pan_id': None, '_groups': {1: <Group group_id=0x0001 name='No name group 0x0001' members={(00:21:2e:ff:ff:03:b4:a4, 1): <zigpy.endpoint.Endpoint object at 0x7f2cf5bbfdd8>, (00:21:2e:ff:ff:03:b4:a4, 242): <zigpy.endpoint.Endpoint object at 0x7f2cf5bc9550>}>, 0: <Group group_id=0x0000 name='No name group 0x0000' members={(00:21:2e:ff:ff:03:b4:a4, 1): <zigpy.endpoint.Endpoint object at 0x7f2cf5bbfdd8>, (00:21:2e:ff:ff:03:b4:a4, 242): <zigpy.endpoint.Endpoint object at 0x7f2cf5bc9550>}>}, '_ieee': 00:21:2e:ff:ff:03:b4:a4, '_nwk': 0, '_nwk_update_id': None, '_ota': <zigpy.ota.OTA object at 0x7f2cf5bbf470>, '_pan_id': None, '_api': <zigpy_deconz.api.Deconz object at 0x7f2cf52f12b0>, '_pending': {}, 'version': 643303168}`

**Comment by Adminiuga** [comment]
What version?

**Comment by zoic21** [comment]
0.9.2 I moved to 0.10.0 and all it's ok. 

And it's fix my issue with last deconz firmware.

Thank a lot
