### ISSUE TITLE
How to investigate on lost device.

### ISSUE THREAD

**Issue by zoic21** [zigpy/zigpy-deconz#134]
Hello,

Î wonder how can I investigate on lost device. I explain yesterday after zigpy restart (I use zigpy on standalone not by HA) I lost one device (Sonoff SNZB-03). Device seem send alert on motion (red led) but no message received on zigpy side (no new log line).

After reinclusion it's work again but I wonder how investigate on that ? 

Thank in advance

**Comment by Adminiuga** [comment]
make sure debug is enabled for zigpy and zigpy_deconz logging components. 
As the the device, get a zigbee sniffer and check what device is actually sending.

**Comment by zoic21** [comment]
Ok thank for your return, all my log is in debug but nothink about this module...

I don't have a sniffer I will take a look on that.

But after more test I think there are an issue on SNZB-03 or my implementation because module send every minute ZoneStatus.0 and immediatly after that ZoneStatus.Alarm_1 on "IAS Zone" cluster.
