### ISSUE TITLE
Is zigpy-deconz ZGP compatible?

### ISSUE THREAD

**Issue by zoic21** [zigpy/zigpy-deconz#135]
Hello,

All in is title, I can't add ZGP device so I wonder if it's an issue with my implementation of zigpy/zigpy-deconz (I don't use HA) or if it's not compatible.

Thank in advance.

**Comment by Adminiuga** [comment]
Not currently. PRs are welcome.

**Comment by zoic21** [comment]
Ok thank for your reply, is it due to zigpy or zigpy-deconz?

**Comment by Adminiuga** [comment]
I haven't looked too much, but I would think it is both. Currently none of the zigpy-based radios do ZGP, as only relatively recently actual radios started to support ZGP

**Comment by zoic21** [comment]
Ok I read implementation of ZGP it's very complex. I don't think I can start this on my own. The only thing I can do is get the manufacturers to send material to those who want to throw it in.
