### ISSUE TITLE
Reset ConBee instructions

### ISSUE THREAD

**Issue by systemcrash** [zigpy/zigpy-deconz#151]
Recent update here shows this new info. 

https://github.com/dresden-elektronik/deconz-serial-protocol

```
2021-01-26
1.20
...
-Describe how the firmware can be rebooted via ‘Watchdog TTL’ parameter
```

Seeking clarification [here](https://github.com/dresden-elektronik/deconz-serial-protocol/issues/7).

But it seems one can reboot the deconz devices. 

Edit: ~~This is especially useful after e.g. Synology devices reboot, and the deconz goes 'offline' until a hot-plug or cold-start (of NAS) is performed.~~ 

~~I don't know how useful this information is - I recall seeing serial port errors when the device is 'offline', so not sure whether even issuing serial commands would be possible.~~

**Comment by Adminiuga** [comment]
Send the PR.
Not clear what you want to update. To be able to reset the device you need to be able to communicate with it. If you are not able to communicate with it, then you can't reset it. Second, zigpy-deconz already using this with a quite short interval, so if it looses communication then the stick is reset.

**Comment by Adminiuga** [comment]
the problem is with docker's `--device` option, as it really does not handle hot-pluggable devices. Any time the conbee resets itself, container looses that device. 
See https://dev.to/jeetparekh/accessing-devices-from-inside-a-docker-container-without-using-the-privileged-flag-1dd8  for a workaround

**Comment by systemcrash** [comment]
Thanks for the workaround. 

A couple of data-points. One does not even need to use those serial drivers out there unless perhaps you want to issue serial commands directly from the Synology OS.

The `--device` flag started working (for USB hot-plug) differently in some later Docker 17 builds, I think. Now I think 18 has this. I include the following in my JSON file which I import for the HA image. 

```json
...
   "devices" : [
       {
           "pathOnHost": "/dev/ttyACM0",
           "PathInContainer": "/dev/ttyACM0",
           "CgroupPermissions": "rwm"
       }
   ],
...
```

Then the image starts up, and the tty device is accessible, however many times I restart HA from HA. 

Restart HA from Docker, however, and the e.g.  `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2415090-if00` device is unavailable for a few minutes with error:

`ERROR (MainThread) [homeassistant.components.zha.core.gateway] Couldn't start deCONZ = dresden elektronik deCONZ protocol: ConBee I/II, RaspBee I/II coordinator`

Despite `/dev/ttyACM0` being available to the image, after restart. If I unplug and hot-plug the USB device, it works immediately. No restart necessary. 🤷  If I just wait an additional minute or two after a docker-restart, then the device comes back. It seems some work has gone into the Docker image so the USB bus is retried now and then. 

My synology runs Docker 18, namely: 

```
# docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

Seems there's a bit of confusing or old information out there.

**Comment by Adminiuga** [comment]
Per my tests, even with the latest docker, devices are not hot plug able. Container instance has to be restarted. Same behavior as with hass os.

**Comment by Adminiuga** [comment]
What is the issue?
