### ISSUE TITLE
Latest Conbee 2 firmware support deCONZ_ConBeeII_0x26720700.bin.GCF

### ISSUE THREAD

**Issue by haralake** [zigpy/zigpy-deconz#170]
I'm using ZHA integration with Conbee 2. I'm interesting to update conbee 2 firmware to latest version deCONZ_ConBeeII_0x26720700.bin.GCF but i don't know if thew latest version supported by zigpy-deconz implementation without issues. Is there anyone using the latest Conbee 2 firmware with ZHA without issues?

**Comment by Adminiuga** [comment]
Upgrade.
Test.
Report the results.
Downgrade if needed.
