### ISSUE TITLE
[zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x21' WARNING

### ISSUE THREAD

**Issue by firstdominator** [zigpy/zigpy-deconz#175]
Hassos : 6.6
Core: 2021.11.5
Supervisor 2021.10.8

Logger: zigpy_deconz.api
Source: /usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py:307
First occurred: 9:05:39 PM (1 occurrences)
Last logged: 9:05:39 PM

No response to 'Command.aps_data_indication' command with seq id '0x21'
[zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x21'

Thanks!

**Comment by Adminiuga** [comment]
Update firmware. If the stick does not reply to a command in 2s when it supposed to reply immediately then you get this warning. 

Newer firmware should have better serial come handling

**Comment by MattWestb** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog
And instruction for updating outside deCONZ https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-windows

**Comment by Elox1991** [comment]
I have the same error. Newest firmware, the stick is on a 2m cord, no wifi interferance but I still get this error 200-300 times in 24h. Any tips? Everything works fine. I have around 41 devices - 31 light bulbs and 10 battery powered (buttons, motion and door sensors).
