### ISSUE TITLE
[REQUEST] Open ZigBee Coordinator Backup Format support for Zigbee network backups and restoring from and to ConBee/RaspBee (deCONZ based adapters)

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-deconz#177]
Request for developers who own ConBee or RaspBee (deCONZ based adapters) and are depending on zigpy-deconz to consider implementing Zigbee network backup and restore tools to zigpy-deconz (or [zigpy-cli](https://github.com/zigpy/zigpy-cli)) supporting "[Open ZigBee Coordinator Backup Format](https://github.com/zigpy/open-coordinator-backup)" as already supported by both [zigpy-znp](https://github.com/zigpy/zigpy-znp) and [bellows](https://github.com/zigpy/bellows) radio libraries:

* https://github.com/zigpy/open-coordinator-backup
* https://github.com/zigpy/zigpy-znp/blob/dev/TOOLS.md#backup-and-restore
* https://github.com/zigpy/bellows#nvram-backup-and-restore

FYI, this is already a popular upgrade and downgrade method among end-users in the ZHA community as seen in examples here:

* https://www.youtube.com/watch?v=ql58ZfXso1M&ab_channel=EverythingSmartHome
* https://community.home-assistant.io/t/backup-your-zha-husbzb-1-stick-and-even-seamlessly-migrate-to-a-new-stick-without-re-pairing/229044/

PS: Also keep in mind that this [Open ZigBee Coordinator Backup Format](https://github.com/zigpy/open-coordinator-backup) is also already in use by the Zigbee2MQTT (Z2M) project.

**Comment by puddly** [comment]
This is already implemented: https://github.com/zigpy/zigpy-cli/pull/2
