### ISSUE TITLE
No response to 'Command.read_parameter' command with seq id '0x02'

### ISSUE THREAD

**Issue by hansdaniels** [zigpy/zigpy-deconz#179]
Hi,
my Conbee II, integrated into Home Assistant via hass.io has stopped working, no longer connects to previously known devices and is unable to find new ones.

I've reinstalled hass.io to the version listed below, started with a blank sheet, but without luck/change. zygpy-deconz fails to start.

What could be the source of this error and how can I fix it?

Thanks for your work (and your help)!

I get the following logs:

```
Logger: zigpy.application
Source: /usr/local/lib/python3.9/site-packages/zigpy/application.py:73
First occurred: 13:51:54 (5 occurrences)
Last logged: 13:53:13

Couldn't start application
``` 

```
Logger: homeassistant.components.zha.core.gateway
Source: components/zha/core/gateway.py:152
Integration: Zigbee Home Automation (documentation, issues)
First occurred: 13:51:54 (5 occurrences)
Last logged: 13:53:13

Couldn't start deCONZ = dresden elektronik deCONZ protocol: ConBee I/II, RaspBee I/II coordinator
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 152, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.9/site-packages/zigpy/application.py", line 69, in new
    await app.startup(auto_form)
  File "/usr/local/lib/python3.9/site-packages/zigpy_deconz/zigbee/application.py", line 67, in startup
    self.version = await self._api.version()
  File "/usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py", line 463, in version
    (self._proto_ver,) = await self[NetworkParameter.protocol_version]
  File "/usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py", line 428, in read_parameter
    r = await self._command(Command.read_parameter, 1 + len(data), param, data)
  File "/usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py", line 313, in _command
    return await asyncio.wait_for(fut, timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

```
Logger: zigpy_deconz.api
Source: /usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py:315
First occurred: 13:51:54 (5 occurrences)
Last logged: 13:53:13

No response to 'Command.read_parameter' command with seq id '0x02'
``` 

```
Logger: zigpy_deconz.api
Source: /usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py:257
First occurred: 13:52:07 (1 occurrences)
Last logged: 13:52:07

Serial '/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2452177-if00' connection lost unexpectedly: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:344
First occurred: 13:51:54 (1 occurrences)
Last logged: 13:51:54

Config entry 'ConBee II - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2452177-if00, s/n: DE2452177 - dresden elektronik ingenieurtechnik GmbH - 1CF1:0030' for zha integration not ready yet; Retrying in background
```

I've updated the firmware of the ConBee II to `deCONZ_ConBeeII_0x26720700.bin.GCF`, but without change.

Using deConz on a Windows 10 PC, I could pair a sensor to it, but I haven't had this luck with Home Assistant (which is no wonder if the integration zigpy-deconz fails to start ...).

My setup is reported like this:

## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 118.5 GB
disk_used | 4.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.11.1)

</details>

**Comment by Adminiuga** [comment]
Restart the container.
Make sure the proper device is passed into the container
Container may not play well with USB hot plugging, if for the some reason the ConBee is reset internally or USB connection is reset, container looses the serial device

**Comment by hansdaniels** [comment]
Thanks, but the problem persists:

Even after a complete restart of my Raspberry PI 4 without any USB (un-)plugging, the described error occurs.

The add-on's config tab lists 2 devices:
```
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2452177-if00
/dev/ttyAMA0
```
With the first, I get the aforementioned errors.
With the second, still no pairing possible, but the errors change:
```
17:30:16:381 device state timeout ignored in state 2
17:30:16:542 device state timeout ignored in state 2
17:30:16:702 device state timeout ignored in state 2
17:30:16:862 device state timeout ignored in state 2
17:30:17:022 device state timeout ignored in state 2
17:30:17:182 device state timeout ignored in state 2
17:30:17:298 try to reconnect to network try=9
17:30:17:342 device state timeout ignored in state 2
17:30:17:502 device state timeout ignored in state 2
17:30:17:662 device state timeout ignored in state 2
17:30:17:822 device state timeout ignored in state 2
17:30:17:982 device state timeout ignored in state 2
17:30:18:142 device state timeout (handled)
17:30:18:221 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
17:30:18:222 device state timeout ignored in state 1
17:30:22:300 failed to reconnect to network try=10
17:30:27:298 reconnect network failed, try later
17:30:27:299 start reconnect to network
17:30:32:298 failed to reconnect to network try=1
17:30:32:864 dev /dev/ttyAMA0
```

Switching back to `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2452177-if00` gives me the old errors again.

**Comment by puddly** [comment]
Those logs look like they're from deCONZ. Did you shut down deCONZ before trying to set up ZHA?

**Comment by hansdaniels** [comment]
you're right, these logs are from deCONZ.
I've posted them because the deCONZ addon fails to start mentioning zigpy-deconz.

I haven't tried to set up ZHA explicitly, I've been trying to use it via the deCONZ addon.
If there is a better/more reliable way, please let me know!

**Comment by puddly** [comment]
If you want to use ZHA, you have to completely disable the deCONZ addon. ZHA is built into Home Assistant and directly talks to the Conbee over its serial port, it doesn't need the deCONZ addon and will not run with it.

This is why your error message contained `(device disconnected or multiple access on port?)`. ZHA and deCONZ are both trying to access the same serial port, which breaks both.

**Comment by hansdaniels** [comment]
Thanks for telling me this!

But sadly, even without the add-on deCONZ (deinstalled) I still can't pair with the ZHA integration.
"Show logs" shows empty space.

Strangely, after removing the ZHA integration using deCONZ/Phoscon only, paring hasn't worked as well.

In the past, ZHA has been working and I liked it.
(at least, when it was working, but I had the deCONZ add-on installed as well and, as you have described, it may have interfered).

Tomorrow I will try from scratch.

**Comment by hansdaniels** [comment]
OK, I've reinstalled HASS from scratch, only used my config from the backup.
I've only activated the deCONZ-ZHA integration and haven't installed the deCONZ add-on:

My network with all devices was found, but all in offline state.
But at least, re-pairing was successful :-) and lights can be toggled again via HASS/ZHA.

Thanks a lot!

**Comment by austin202220** [comment]
I had similar issues on my end today. I restored multiple backups, from before and after the incident. I finally found that at some point I unplugged the conbee ii usb stick and when I plugged it back into the rpi4 I used a different usb port on accident. Finally once I moved it back to the original usb port and reloaded my most recent backup it all started working again.

So it appears that once conbee ii is installed you need to keep it on that same usb port forever, you cant move it to a different usb slot.
