### ISSUE TITLE
"Unknown command received: 25"

### ISSUE THREAD

**Issue by darkskiez** [zigpy/zigpy-deconz#18]
I've tried pairing a tradfri switch, a hue motion sensor, a  Xiaomi Aqara temperature sensors and a door sensors, I see a few frames printed  and sometimes the Unknown command received:25

I upgraded zigpy-deconz to 0.1.1 release against the lastest 0.88 build of homeassistant, but no luck with anything pairing.

Feb 21 09:58:28 hass hass[2302]: 2019-02-21 09:58:28 DEBUG (MainThread) [zigpy_deconz.api] Version response: 262f0500

Feb 21 00:58:49 hass hass[2786]: 2019-02-21 00:58:49 DEBUG (MainThread) [zigpy_deconz.api] Write parameter permit_join: SUCCESS
Feb 21 00:58:50 hass hass[2786]: 2019-02-21 00:58:50 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c190012000b00035c70e902008d1500ffec
Feb 21 00:58:51 hass hass[2786]: 2019-02-21 00:58:51 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Broadcast not implemented.
Feb 21 00:58:51 hass hass[2786]: 2019-02-21 00:58:51 DEBUG (MainThread) [zigpy_deconz.api] Command write_parameter (2, 33, b'<')
Feb 21 00:58:51 hass hass[2786]: 2019-02-21 00:58:51 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x0b190009000200213c
Feb 21 00:58:51 hass hass[2786]: 2019-02-21 00:58:51 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0b19000800010021
Feb 21 00:58:51 hass hass[2786]: 2019-02-21 00:58:51 DEBUG (MainThread) [zigpy_deconz.api] Write parameter permit_join: SUCCESS
Feb 21 00:58:52 hass hass[2786]: 2019-02-21 00:58:52 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c1a0012000b00035c70e902008d1500ffeb
Feb 21 01:04:00 hass hass[2786]: 2019-02-21 01:04:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x191b0016000f008c3094354300c70a000022bd60d392
Feb 21 01:04:00 hass hass[2786]: 2019-02-21 01:04:00 DEBUG (MainThread) [zigpy_deconz.api] Unknown command received: 25
Feb 21 01:04:00 hass hass[2786]: 2019-02-21 01:04:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x191c0016000f008c3094354300c70a000022bd60d392
Feb 21 01:04:00 hass hass[2786]: 2019-02-21 01:04:00 DEBUG (MainThread) [zigpy_deconz.api] Unknown command received: 25

**Comment by damarco** [comment]
Which firmware version are you running? If you are running zigpy-deconz 0.1.1 it should be logged (debug level) during startup.

**Comment by darkskiez** [comment]
Like the first line in the log above =)) 262f0500

**Comment by damarco** [comment]
Sorry, missed that one. :) What is the result after pairing a device? Do you see any entities in home assistant? Can you share the full debug log from pairing the aqara temp sensor?

**Comment by darkskiez** [comment]
I'll try again when I get home because I can't remember which log line is from which device, I've never successfully paired anything, nothing appears as an entity.

When I press permit, then I press a pairing button on one of the devices and I see a "frame received" log line or two, but nothing else appears in the logs, and no entities show up in HA.

Feb 21 00:58:52 hass hass[2786]: 2019-02-21 00:58:52 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c1a0012000b00035c70e902008d1500ffeb

**Comment by damarco** [comment]
Are any of those devices already joined through deconz/phoscon (using the same stick)?

**Comment by dmulcahey** [comment]
@darkskiez any chance you installed the new zigpy-deconz from pypi and not the new zigpy-homeassistant too?

**Comment by darkskiez** [comment]
No, I've not joined any devices to deconz/phoscon, these are new devices never joined to a network.

I used only the new zigpy-deconz in a little bit of kludgy way by bumping the version listed in:
<virtualenvpath>/lib/python3.5/site-packages/homeassistant/components/zha/__init__.py

**Comment by damarco** [comment]
Please share the full debug log from startup to the pairing attempt. Do you have a ConBee or RaspBee device?

**Comment by Adminiuga** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158#issuecomment-466116442
