### ISSUE TITLE
Jeedom installation - concurrent.futures._base.TimeoutError

### ISSUE THREAD

**Issue by Floflobel** [zigpy/zigpy-deconz#188]
Hello,

I am a Jeedom user and I use the Zigbee plugin which from what I could see uses zigpy & zigpy-deconz.

I have a Conbee II key and I can't get it to work anymore. I have tested a lot of things but I always get an error that is returned.

I'm calling for your help to try to understand where my problem could come from, I tried to look at the python code but not being a developer, I admit I'm a bit lost.

Here is the set of tests I performed:
- Update the firmware of the Conbee II key via a Windows PC
- Change the USB port of the Conbee II key
- Check that it was not on a USB 3.0 port
- Reset the zigpy database
- Move the key with a USB extension cable
- Reboot my server completely
- Bought a new Conbee II key to make sure it was not defective
- Re-create my Jeedom installation from scratch to make sure I didn't do anything wrong
- And I tried to get support on the Jeedom forum but unfortunately nobody could help me

Here is the information about my set-up:
- Server: Debian 11 with KVM/QEMU to virtualize my jeedom VM
- VM Jeedom: Debian 10 with Conbee II pasthrough
- Zigpy version:
```
zigpy               0.43.0
zigpy-deconz        0.14.0
zigpy-xbee          0.14.0
zigpy-zigate        0.8.0
zigpy-znp           0.7.0
```

Other informations:
- Topic in French about my problem: https://community.jeedom.com/t/impossible-de-lancer-le-daemon-zigbee/79141/12
- I see this similar issue: https://github.com/zigpy/zigpy-deconz/issues/179

I will add the logs in debug mode of my Jeedom installation which uses zigpy:
[zigbeed_1(1).log](https://github.com/zigpy/zigpy-deconz/files/8249115/zigbeed_1.1.log)

Thank you in advance to those who can help me try to understand and solve my problem.

**Comment by puddly** [comment]
zigpy-deconz has not seen any new releases in four months. Try unplugging the Conbee and plugging it in again.

**Comment by Floflobel** [comment]
I have already done this (with a full reboot of the server) and as I specified, I also tried with a brand new key.

**Comment by Adminiuga** [comment]
It is the very first serial command and you don't get a response to it. Check the serial port and USB passthrough configuration. 
You could try installing zigpy-cli on the host and trying getting that working, to confirm the stick itself is working.

**Comment by Hedda** [comment]
Non-developer end-users help and support with Jeedom and Jeedom's Zigbee Plugin has to go through the Jeedom community:

https://community.jeedom.com

PS: Jeedom Zigbee Plugin is also part of a partially closed system an not quite in the spirit of FOSS (Free and Open Source Software) as the code is not shared via git on https://github.com/jeedom but require that you purchase and get it via their Jeedom market.

**Comment by Floflobel** [comment]
Thank you for your answers.

The problem was solved by migrating from a VM under KVM/QEMU to a container under LXD. So I must have a problem with my VM virtualization system.
