### ISSUE TITLE
zigpy-deconz (ConBee/RaspBee adapter) and ZHA support for joining/pairing via install code and qr code?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-deconz#214]
UPDATE: This is dependent on dresden-elektronik's deCONZ (ConBee) developers first adding support and documenting it, see:

* https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20

Back-story; Some users of Home Assistant’s [ZHA integration](https://www.home-assistant.io/integrations/zha) with ConBee and RaspBee Zigbee Coordinator adapters from dresden elektronik have posted that they could not join/pair their Bosch Smart Home Zigbee devices that required an install code, and then some other users replied to that post saying that install code (and qr code?) support is not implemented in this zigpy-deconz radio library for zigpy which the ZHA integration depends on. Is that true?

https://github.com/zigpy/zigpy-deconz/blob/80041b9dbf334e0224b95081fcd49bb2da3e8c5d/zigpy_deconz/zigbee/application.py#L108

Just reporting this issue reported in the Home Assistant community forum:

https://community.home-assistant.io/t/bosch-thermostat-2/492845/10

https://community.home-assistant.io/t/bosch-thermostat-2/492845/11

The first device in question was the [Bosch Thermostat II 230 V (BTH-RA / BTH-RM230Z)](https://www.zigbee2mqtt.io/devices/BTH-RA.html), however, I understand that some people using deCONZ or Zigbee2MQTT have reported the same issue with a few other Bosch-branded Zigbee devices, like [Bosch Smoke Alarm II (BSD-2)](https://www.zigbee2mqtt.io/devices/BSD-2.html), Bosch Door/window contact II (RBSH-SWD-ZB), and Bosch BWA-1 water sensor, all of which require adding the install code to pair/join.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6476

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6421

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5190

I do not have a ConBee or RaspBee setup as Zigbee Coordinator myself any longer so can not replicate to confirm or deny but think this should be tracked if a feature is missing since supported by Silicon Labs and Texas Instruments based Zigbee Coordinator adapters via their respective radio library for zigpy. 

PS: Both [Silicon Labs (bellows)](https://github.com/zigpy/bellows) and [Texas Instruments (zigpy-znp)](https://github.com/zigpy/zigpy-znp) radio libraries for zigpy do support install code (and qr code) or?

https://github.com/zigpy/bellows/blob/8549f277027245f5e63ce1341b7e6c5c75381899/bellows/zigbee/application.py#L845-L866

https://github.com/zigpy/zigpy-znp/blob/c4db8d1151b5a999ead73480faea4ea01b7cb7d7/zigpy_znp/zigbee/application.py#L338-L377

**Comment by puddly** [comment]
That's correct. There's no documented way to use install codes with the Conbee.

**Comment by Hedda** [comment]
Reposted to https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20 in hope @manup or someone else from Dresden Elektronik can assist.

**Comment by Hedda** [comment]
> That's correct. There's no documented way to use install codes with the Conbee.

Is zigpy-deconz the only radio library for zigpy that doea not support this? Is there tests for this in the different zigpy radio libraries in order to check and track feature parity between them?

**Comment by puddly** [comment]
> Is zigpy-deconz the only radio library for zigpy that doea not support this?

It's only supported on EZSP and ZNP coordinators. No other firmwares support it (and likely never will, aside from the Conbee).

**Comment by Hedda** [comment]
FYI, [ChrisHae](https://github.com/ChrisHae)'s reply to https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20 indicates this is in their roadmap for future deconz firmware.

Also updated the documentation for Home Assistant's ZHA integration to try to clearify that this is is a manufacturer limitation:

https://www.home-assistant.io/integrations/zha#limitations

"**_Support for commissioning Zigbee 3.0 devices via “Install Code” or “QR Code” via the ‘zha.permit’ service has so far only been implemented for ‘ezsp’ (Silicon Labs EmberZNet) or ‘znp’ (Texas Instruments) radio type in ZHA. Other radio types are missing support in their respective [radio libraries for zigpy](https://github.com/zigpy/) or manufacturer’s firmware commands/APIs._**"

**Comment by Hedda** [comment]
FYI, it seems deconz firmware support zigbee install codes as dresden-elektronik now implemented support in deconz-rest-plugin:

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6791

Interestingly @SwoopX mentions in that PR that the code to derive the required hash is ported from the zigpy implementation.

https://github.com/dresden-elektronik/deconz-rest-plugin/commit/24c7ff9d3047b7a6bde698e56d734120b63025ee

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.22.0-beta

**_Enhancements: Enable usage of zigbee install codes https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6791_**

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6476

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6421

**Comment by Hedda** [comment]
FYI, Dresden-Elektronik developer has now updated deCONZ Serial Protocol documentation to 1.22 with info on install codes. See:

_Originally posted by @manup in https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20#issuecomment-2344518503_

_Sorry this took a while, I had reworked the document since the former .docx based one was messy to update. The document references are in a bit rough shape but that's for another version. The new version 1.22 has now been uploaded http://deconz.dresden-elektronik.de/raspbian/deCONZ-Serial-Protocol_en_1.22.pdf_

_There is a new small section **6.2.3 Zigbee Install Codes** which describes the basic usage._

_As reference how it works in deCONZ the following sources might be helpful as well:_

_Calculating the derived Link Key from Zigbee Install Code (I think ZHA and Z2M already have similar code):
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/crypto/mmohash.cpp_

_How the install code is processed by the REST-API and set to the firmware:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/0e2dc155e85893b439f354cd5d764e414ad0ed0c/rest_devices.cpp#L1090_

_Originally posted by @manup in https://github.com/dresden-elektronik/deconz-serial-protocol/issues/20#issuecomment-2344518503_

```
6.2.3 Zigbee Install Codes
The Serial Protocol and firmware doesn’t support Zigbee Install Codes directly. In order to join a
device via Install Code, a device specific Link Key needs to be derived from the Install Code by
the host application.
This 16-byte Link Key together with the device MAC address can than be configured by a Write Parameter Request (0×0B) for the Link Key parameter (0×19).
Once configured, during joining process, the device will receive the Network Key encrypted with
the Link Key instead of the global Truster Center Link Key.
```

A C++ OpenSSL reference implementation for the key derivation can be found at:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/crypto/mmohash.cpp

**Comment by puddly** [comment]
This has been implemented since https://github.com/zigpy/zigpy-deconz/releases/tag/0.22.0 in November 2023.

**Comment by Hedda** [comment]
> This has been implemented since https://github.com/zigpy/zigpy-deconz/releases/tag/0.22.0 in November 2023.

@puddly Was it? Changelog does not mention "install code"? (I do not actually have a ConBee any longer so can not test myself).

Home Assistent’s ZHA integration docs need updating if device provisioning via install code and qr code is fully now supported via zigpy-deconz when using ConBee II and ConBee III radio adapters with the same functionality as available when using bellows (Silabs EZSP) and zigpy-znp (Texas Instruments ZNP):

* https://www.home-assistant.io/integrations/zha#limitations

"_**Support for commissioning Zigbee 3.0 devices via “Install Code” or “QR Code” via the zha.permit action has so far only been implemented for ‘ezsp’ (Silicon Labs EmberZNet) or ‘znp’ (Texas Instruments) radio type in ZHA. Other radio types are missing support in their respective [radio libraries for zigpy](https://github.com/zigpy/) or manufacturer’s firmware commands/APIs.**_"

**Comment by Hedda** [comment]
This issue should probably be reopened as accordibg to @manup install code working was only a hack that only worked with ConBee II adapter but not ConBee III adapters, however they now released new firmware for both ConBee II and ConBee III that adds proper support for install code joining:

 _Originally posted by @Hedda in [#447](https://github.com/zigpy/zha/issues/447#issuecomment-3022603142)_

> For reference, dev branch of zigbee-herdsman (library used by Zigbee2MQTT) contains a completely refactored [deconz adapter implementation](https://github.com/Koenkk/zigbee-herdsman/tree/master/src/adapter/deconz) with much of their code rewritten by @manup (who works for Dresden-Elektronik) and Z2M testers reported that Bosch install codes now work with ConBee II using this:
> 
> - https://github.com/Koenkk/zigbee-herdsman/pull/1417
> 
> Note that they already released new firmware for ConBee II and ConBee III to match new features, including proper support for install code in that new ConBee firmware.
> 
>   - https://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D
> 
> FYI, also note that manup look to have posted other relevant comments in that pull request, both about improvementts that he have made and possible additional improvements that could maybe be done in the future:
> 
> - *Robustness in sending ZCL / ZDO commands:
> The old driver is rather optimistic and didn't handle errors in a defined manner. The rewrite is in par with the deCONZ reference implementation and handles error paths explicitly by tracking timeouts and transaction sequence numbers. Especially here the queue handling is streamlined now to never do "fire and forget" commands and having untracked Promises.*
> 
> - *Reconfiguration and channel change: The old driver is only re-configuring some of the network parameters and doesn't send ZDP channel change commands to move a network to a new channel if the configuration was changed. The PR handles this fully within the new state machine. Further any misconfiguration gets handled same as in deCONZ reference.*
> 
> - *Backup support, this also handles automatic migration between ConBee I, II, III and RaspBee I/II.*
> 
> - *Not part of this PR is Zigbee Install Code support. Although at least the ConBee II firmware supports these with a hack, we would like to add proper firmware support first before adapting this in the driver in a future PR.*
> 
> - *Install Codes will be added in a later PR after refactoring the firmware for ConBee/RaspBee 2 and 3.*
> 
> - *APS ACKs are now enabled for all unicast requests.*
> 
> - *Personal wishlist for a future Adapter interface:
> (to simplify adapter development a lot 😄 )
> An adapter should only provide an interface for `APS Request, Confirmation and Indication. And handling of these moved into z2m controller. The adapters shouldn't know anything about ZCL, ZDO requests or tracking their responses. With that only z2m controller needs robust handling implemented in one place which works the same for every coordinator. Imho this would reduce the code size of adapters a lot and bugs could be ironed out more broadly in one place.*
> 
> - *Backup is now implemented (with an empty device list untill Install Codes / Link Keys get refactored in firmware).*
> 
> - *The implementation and logic was aligned to the Ember adapter. From a users perspective I'm still not sure how to apply a backup other than to put the coordinator_backup.json in the data directory, the https://www.zigbee2mqtt.io/guide/adapters/#coordinator-backups is a bit vague here. In theory the backup should also allow to switch coordinator vendors (sans the Install Code / Link Keys) but I haven't tested this. All other parameters including mac address get synced, but there might be troubles when switching between Zigbee R21 - R23 coordinators.*
> 
> - *Channel Change works now too and I made a few tests to move the network around.*
> 
> - *Touchlink is currently not planned for near term.*
> 
> - *Changing the transmit power is something we do consider to add. Technically it's a small change. But the catch is that the firmware is already at the maximum allowed tx power and going above that can get vendors in legal trouble at least in the EU. So the update will eventually only provide a way to reduce the tx power, which still can be useful to limit sniffer visibility when joining devices and while the network key is transmitted.*
