### ISSUE TITLE
Devices array is empty in backup file

### ISSUE THREAD

**Issue by shlomki** [zigpy/zigpy-deconz#215]
Hey, thanks for the awesome work you've all done here.

I'm trying to backup my Conbee II coordinator but for some reason no devices are being listed in the backup json.

Some background:
- I'm using using zigbee2mqtt installed in a docker container on a linux host machine (Unraid).
- I have a Conbee II as my coordinator, firmware version 0x26580700 as recommended by Z2M.
- I have 93 devices paired in Z2M, all working great.
- I've stopped the Z2M container before running zigpy-cli on the host machine.
- Other commands on Z2M seem to be working great (info, energy-scan).

The output json of the backup command looks like this:
```
{
    "metadata": {
        "version": 1,
        "format": "zigpy/open-coordinator-backup",
        "source": "zigpy-deconz@0.19.2",
        "internal": {
            "creation_time": "2023-02-22T18:00:07.541322+00:00",
            "node": {
                "ieee": "REDACTED",
                "nwk": "0000",
                "type": "coordinator"
            },
            "network": {
                "tc_link_key": {
                    "key": "REDACTED",
                    "frame_counter": 0
                },
                "tc_address": "REDACTED",
                "nwk_manager": "0000"
            },
            "link_key_seqs": {},
            "deconz": {
                "version": 643303168
            }
        }
    },
    "stack_specific": {},
    "coordinator_ieee": "REDACTED",
    "pan_id": "REDACTED",
    "extended_pan_id": "dddddddddddddddd",
    "nwk_update_id": 2,
    "security_level": 5,
    "channel": 25,
    "channel_mask": [
        25
    ],
    "network_key": {
        "key": "REDACTED",
        "sequence_number": 0,
        "frame_counter": 0
    },
    "devices": []
}

```

Any ideas why the paired devices aren't being backed up?
Am I running zigpy-cli correctly, on the host machine when the z2m container is down?
Any help would be appreciated.

**Comment by puddly** [comment]
> Any ideas why the paired devices aren't being backed up?

The Conbee just doesn't store this information, it's by design. It expects child data to be loaded at runtime by your integration:

https://github.com/zigpy/zigpy-deconz/blob/80041b9dbf334e0224b95081fcd49bb2da3e8c5d/zigpy_deconz/zigbee/application.py#L464-L497

So the backup is complete. I also noticed this in your backup:

```
        "frame_counter": 0
```

Make sure you update your Conbee's firmware to the latest version, as older versions don't let you read out the frame counter and the backup will be incomplete.

**Comment by shlomki** [comment]
Thanks for the quick and insightful reply @puddly!

> The Conbee just doesn't store this information, it's by design

So, since the Conbee doesn't store child data, does this mean I won't be able to migrate to another coordinator by restoring this backup to another coordinator?

> Make sure you update your Conbee's firmware to the latest version, as older versions don't let you read out the frame counter and the backup will be incomplete.
Z2M's documentation says there's currently a problem with higher firmware versions which cause devices to drop connection, so I guess I'll wait until the moment I change coordinators to upgrade, if it's even relevant to migrate coordinators without repairing.

**Comment by puddly** [comment]
No, the child data just isn't necessary. The coordinator won't know about children until they start talking to it but this isn't a problem and it's nothing to worry about. People have migrated to/from the Conbee many times with ZHA, which uses these libraries.

**Comment by shlomki** [comment]
Thanks for all your help!
