### ISSUE TITLE
Not geting the firmware version of ConBee II with zigpy-deconz 0.22.0

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy-deconz#236]
in zigpy-deconz 0.21.1, we get version like here after in the log, and we've git it into self.version

> 2023-11-20 18:40:15,482 DEBUG   :Command Command.version (0,)
> 2023-11-20 18:40:15,482 DEBUG   :Send: 0x0d0300090000000000
> 2023-11-20 18:40:15,486 DEBUG   :Frame received: 0x0d0300090000077926
> 2023-11-20 18:40:15,486 DEBUG   :Received command version[645465856]
> 2023-11-20 18:40:15,487 DEBUG   :Version response: 26790700

in zigpy-deconz 0.22.0 I didn't see the Command.version(0,) sent but instead :Sending CommandId.version{'reserved': 0} , which doesn't provide the Firmwar version of ConBee II

> 2023-11-20 18:35:03,532 DEBUG   :Sending CommandId.version{'reserved': 0} (seq=2)
> 2023-11-20 18:35:03,534 DEBUG   :Send: 0d0200090000000000
> 2023-11-20 18:35:03,538 DEBUG   :Frame received: 0x0d0200090000077926
> 2023-11-20 18:35:03,541 DEBUG   :Received command CommandId.version{'status': <Status.SUCCESS: 0>, 'frame_length': 9, 'version': FirmwareVersion(reserved=0, platform=<FirmwarePlatform.Conbee_II: 7>, minor=121, major=38)} (seq 2)
> 2023-11-20 18:35:03,544 DEBUG   :Sending CommandId.device_state{} (seq=3)
>

**Comment by pipiche38** [comment]
Full logs are available for your informations
[PluginZigbee_09-deconz-0.21.1.log](https://github.com/zigpy/zigpy-deconz/files/13417929/PluginZigbee_09-deconz-0.21.1.log)
[PluginZigbee_09-deconz-0.22.0.log](https://github.com/zigpy/zigpy-deconz/files/13417930/PluginZigbee_09-deconz-0.22.0.log)

**Comment by pipiche38** [comment]
looks like version is now store in the network_info meta data.

**Comment by puddly** [comment]
The device firmware version is in `node_info.version` now
