### ISSUE TITLE
Exception: write_parameter, status: 4

### ISSUE THREAD

**Issue by syphernl** [zigpy/zigpy-deconz#8]
After configuring in HomeAssistant I'm seeing this error. The device worked just fine before with Deconz, but from HA via this library I'm getting:

```
Traceback (most recent call last):
  File "/srv/hass/lib/python3.6/site-packages/zigpy_deconz/zigbee/application.py", line 34, in _reset_watchdog
    await self._api.write_parameter(NETWORK_PARAMETER['watchdog_ttl'][0], 3600)
  File "/srv/hass/lib/python3.6/site-packages/zigpy_deconz/api.py", line 207, in write_parameter
    timeout=COMMAND_TIMEOUT
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
```

Any thoughts as to what this can be? If you need any more info, please let me know!

**Comment by damarco** [comment]
Make sure ConBee/RaspBee has the latest firmware (update through latest deconz/phoscon). Ignore the failed watchdog_reset command for a moment and see if it also fails after running for a while. It should be triggered every 20 minutes.

**Comment by damarco** [comment]
Can you post the full debug log beginning with HA startup? Which device are you trying to pair?

**Comment by damarco** [comment]
The timeout on cluster bind is expected, as Xiaomi devices do not fully follow the standard.

**Comment by damarco** [comment]
@syphernl Can we close this?
