### ISSUE TITLE
Checksum error every hour

### ISSUE THREAD

**Issue by darkskiez** [zigpy/zigpy-deconz#9]
0x0a5261737042656520426f6f746c6f61646572207072656d69756d0a566572732e20312e30320a6275696c6420323031332f30382f30310a5354415254494e47204150
Jan 29 18:37:06 hass hass[772]: 2019-01-29 18:37:06 WARNING (MainThread) [zigpy_deconz.uart] Invalid checksum: 0x500a, data: 0x0a5261737042656520426f6f746c6f61646572207072656d69756d0a566572732e20312e30320a6275696c6420323031332f30382f30310a5354415254494e47204150
Jan 29 19:37:08 hass hass[772]: 2019-01-29 19:37:08 WARNING (MainThread) [zigpy_deconz.uart] Invalid checksum: 0x500a, data: 0x0a5261737042656520426f6f746c6f61646572207072656d69756d0a566572732e20312e30320a6275696c6420323031332f30382f30310a5354415254494e47204150
Jan 29 20:37:11 hass hass[772]: 2019-01-29 20:37:11 WARNING (MainThread) [zigpy_deconz.uart] Invalid checksum: 0x500a, data: 0x0a5261737042656520426f6f746c6f61646572207072656d69756d0a566572732e20312e30320a6275696c6420323031332f30382f30310a5354415254494e47204150
Jan 29 21:37:14 hass hass[772]: 2019-01-29 21:37:14 WARNING (MainThread) [zigpy_deconz.uart] Invalid checksum: 0x500a, data: 0x0a5261737042656520426f6f746c6f61646572207072656d69756d0a566572732e20312e30320a6275696c6420323031332f30382f30310a5354415254494e47204150

Followed by a network rejoin..

Jan 29 21:37:14 hass hass[772]: 2019-01-29 21:37:14 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e010007008100
Jan 29 21:37:14 hass hass[772]: 2019-01-29 21:37:14 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [129, 0]
Jan 29 21:37:14 hass hass[772]: 2019-01-29 21:37:14 DEBUG (MainThread) [zigpy_deconz.api] Network state: JOINING
Jan 29 21:37:14 hass hass[772]: 2019-01-29 21:37:14 DEBUG (MainThread) [zigpy_deconz.api] Data request queue full.
Jan 29 21:37:16 hass hass[772]: 2019-01-29 21:37:16 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e02000700b200
Jan 29 21:37:16 hass hass[772]: 2019-01-29 21:37:16 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [178, 0]
Jan 29 21:37:16 hass hass[772]: 2019-01-29 21:37:16 DEBUG (MainThread) [zigpy_deconz.api] Network state: CONNECTED

I haven't been able to pair my tradfri switch yet, I think it needs me to initiate a touchlink search somehow. My other devices are currently in use with a hue bridge and I haven't been able to try with them yet so I don't know if it works at all, just giving this early feedback.

**Comment by damarco** [comment]
The checksum error is from a bootloader message after a watchdog reset. This should be fixed in the released version. If you enable debug logging, do you see any watchdog messages?

**Comment by darkskiez** [comment]
This was from the 0.0.1 release pulled in by homeassistant...

Feb 05 15:21:45 hass hass[8016]: 2019-02-05 15:21:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Feb 05 15:21:45 hass hass[8016]: Traceback (most recent call last):
Feb 05 15:21:45 hass hass[8016]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Feb 05 15:21:45 hass hass[8016]:     result = coro.send(None)
Feb 05 15:21:45 hass hass[8016]:   File "/home/homectl/hass/lib/python3.5/site-packages/zigpy_deconz/zigbee/application.py", line 34, in _reset_watchdog
Feb 05 15:21:45 hass hass[8016]:     await self._api.write_parameter(NETWORK_PARAMETER['watchdog_ttl'][0], 3600)
Feb 05 15:21:45 hass hass[8016]:   File "/home/homectl/hass/lib/python3.5/site-packages/zigpy_deconz/api.py", line 207, in write_parameter
Feb 05 15:21:45 hass hass[8016]:     timeout=COMMAND_TIMEOUT
Feb 05 15:21:45 hass hass[8016]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
Feb 05 15:21:45 hass hass[8016]:     return fut.result()
Feb 05 15:21:45 hass hass[8016]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Feb 05 15:21:45 hass hass[8016]:     raise self._exception
Feb 05 15:21:45 hass hass[8016]: Exception: write_parameter, status: 4

**Comment by damarco** [comment]
How often do you see that message of a failed watchdog ttl command? Only after startup or every 20 minutes? Which firmware version are you running?
